# Generated by Django 3.0.7 on 2021-10-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='age',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gender',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
