# Generated by Django 3.0.7 on 2021-10-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Photo')),
            ],
        ),
    ]
