# Generated by Django 3.0.7 on 2021-10-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20211025_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='photo',
            new_name='add',
        ),
    ]
