# Generated by Django 3.0.7 on 2021-10-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_auto_20211025_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='age',
            field=models.CharField(default=22, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='gender',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
