# Generated by Django 3.2.9 on 2021-11-22 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_auto_20211026_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
