# Generated by Django 3.2.9 on 2021-11-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_case_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='email',
        ),
    ]
