# Generated by Django 3.2.9 on 2021-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_remove_case_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
