# Generated by Django 3.2.9 on 2022-02-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_alter_case_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.case')),
            ],
        ),
    ]
