# Generated by Django 3.2.9 on 2022-02-21 14:34

from django.db import migrations, models
import testApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_caseimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to=testApp.models.path_and_rename),
        ),
    ]
